### ISSUE TITLE
PSLF python API

### ISSUE THREAD

**Issue by AadilLatif** [GMLC-TDC/PSLF-wrapper#2]
Hi, 

I work at NREL and have installed PSLF on my local machine. I am however unble to find the python API you seem to use fo the wrapper. Does the API come withe the PSLF installer or does it come as a seperate package or was it a one off effort foe the HELICS project? Also sorry using this platform but I was unbale to fing any contact information on github.

Best regards,
Aadil Latif

**Comment by kdheepak** [comment]
The HELICS python wrapper can be installed with conda, so presumably you are asking about the PSLF python wrapper / API? My understanding is that it comes installed with a licensed version of PSLF on Windows. I'm pinging @shwethanidd for additional information.

**Comment by shwethanidd** [comment]
There are some instructions in https://github.com/GMLC-TDC/PSLF-wrapper.git for HELICS to PSLF integration. We tested for a single standalone case. We couldn't get further as PSLF’s dynamic power flow simulation API was not ready.

**Comment by kdheepak** [comment]
PSLF's steady state Python API comes with an installation of PSLF?

**Comment by huangrenke** [comment]
I think we test this PSLF python APIs with a special version of PSLF directly provided by GE. You need to contact GE to get this special version of PSLF support the python APIs.
